language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

# run build against nightly but allow them to fail
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

# faster builds on new travis setup not using sudo
sudo: false

services:
    - memcached

# cache vendor dirs
cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer self-update

before_script:
    # by default, --remote is not used on travis
    - git submodule update --remote --force
    - composer install

script:
    - vendor/bin/phpstan analyse -c phpstan.dist.neon
    - php data/bin/check_configuration.php
    - php data/bin/symfony symfony:test --trace
